services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
        resources:
            limits:
              cpus: "0.15"
              memory: "15MB"
  api1: &api
    image: rinha
    hostname: api
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - SERVER_ID=1
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"
  api2:
    <<: *api
    hostname: api2
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-fallback:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-default:8080
      - SERVER_ID=2
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true